spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          filters:
      routes:
      - id: authservice
        uri: lb://authservice
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix= 1
<#foreach db in base.schemas>
      - id: ${db.serviceName}-service
        uri: lb://${db.serviceName}-service
        predicates:
        - Path=/${db.serviceName}-service/**
        filters:
        - StripPrefix= 1
</#foreach>
elegent:
  security:
    login-strategies:
      - type: admin
        strategy: username_password
        secret-key: elegent
        ttl: 2
    verifier:
      header:
        type: login-type
        token: user-token
      ignore-url:  # 忽略地址，不用登录也可以访问的地址
        - POST/login
        - POST/logout
      privilege-url: #特权地址，所有登录用户都可以访问的地址
        - GET/user/current-user
      privilege-user:
        - admin