spring:
  datasource:
    url: jdbc:mysql://${base.conn.ip}:${base.conn.port}/auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: ${base.conn.username}
    password: ${base.conn.password}
ribbon:
  #单位ms,请求连接的超时时间，默认1000
  #ConnectTimeout: 500
  #单位ms,读取数据的超时时间，默认1000
  #ReadTimeout: 3000
  #对所有操作请求都进行重试
  #设置为true时，会对所有的请求进行重试，若为false只会对get请求进行重试
  #如果是put或post等写操作，
  #如果服务器接口没做幂等性，会产生不好的结果，所以OkToRetryOnAllOperations慎用。
  #默认情况下,GET方式请求无论是连接异常还是读取异常,都会进行重试
  #非GET方式请求,只有连接异常时,才会进行重试
  #OkToRetryOnAllOperations: false
  #切换实例的重试次数，默认为1
  #MaxAutoRetriesNextServer: 2
  #如果不配置ribbon的重试次数
  #对当前实例的重试次数,默认为0
  #MaxAutoRetries: 3
  eager-load:
    enabled: true
    clients: 
elegent:
  security:
    login-strategies:
      - type: admin
        strategy: username_password
        secret-key: elegent
        ttl: 2